{
 "title": "Plex Data",
 "tags": [
  "plex",
  "influxdb",
  "python"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ceph",
    "query": "show tag values with key = \"host\""
   },
   {
    "name": "mediaservers",
    "query": "show tag values with key = \"host\""
   }
  ]
 },
 "panels": [
  { "title": "Plex Media Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Plex Streams",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "active_streams",
     "select": [
      [
       { "params": [ "active_streams" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "All" }
     ]
    }
   ]
  },
  {
   "title": "Movies",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "libraries",
     "query": "SELECT last(\"items\") FROM \"autogen\".\"libraries\" WHERE (\"lib_name\" = 'Movies')",
     "select": [
      [
       { "params": [ "items" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "lib_name", "operator": "=", "value": "Movies" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "libraries",
     "query": "SELECT last(\"items\") FROM \"libraries\" WHERE (\"host\" = '10.0.10.175' AND \"lib_name\" = 'TV Shows')",
     "select": [
      [
       { "params": [ "items" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "10.0.10.175" },
      { "condition": "AND", "key": "lib_name", "operator": "=", "value": "TV Shows" }
     ]
    }
   ]
  },
  {
   "title": "Seasons",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "libraries",
     "query": "SELECT last(\"seasons\") FROM \"libraries\" WHERE (\"host\" = '10.0.10.175' AND \"lib_name\" = 'TV Shows')",
     "select": [
      [
       { "params": [ "seasons" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "lib_name", "operator": "=", "value": "TV Shows" }
     ]
    }
   ]
  },
  {
   "title": "Episodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "libraries",
     "query": "SELECT last(\"episodes\") FROM \"libraries\" WHERE (\"host\" = '10.0.10.175' AND \"lib_name\" = 'TV Shows')",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "lib_name", "operator": "=", "value": "TV Shows" }
     ]
    }
   ]
  },
  {
   "title": "Active Plex Streams",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "lib_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "libraries",
     "query": "SELECT last(\"user\") AS \"User\", \"player\" AS \"Client\", \"media_type\" AS \"Media Type\", \"title\" AS \"Title\", \"grandparent_title\" AS \"Series\", \"parent_title\" AS \"Season\",  \"year\" AS \"Year\",  \"resolution\" AS \"V.Quality\", \"container\" AS \"V.Container\", \"video_codec\" as \"V.Codec\", \"video_framerate\" as \"V.Framerate\", \"audio_codec\" AS \"A.Codec\", \"transcode_summary\" AS \"Transcode\", \"length_ms\" AS \"Duration\", \"position_ms\" as \"Position\", \"pos_percent\"  AS \"Playback %\",  \"status\" AS \"Status\" FROM \"now_playing\" WHERE time > now() - 10s GROUP BY \"session_id\"",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Ceph Cluster Utilization",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 12 },
   "format": "percent",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"osd_bytes_used\")  /  last(\"osd_bytes\") * 100 FROM \"ceph\"",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "device",
       "operator": "=",
       "value": "192.168.1.128:6789,192.168.1.129:6789:/"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 12 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ceph",
     "select": [
      [
       { "params": [ "osd_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Media Pool Utilization",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 12 },
   "format": "percent",
   "targets": [
    {
     "measurement": "disk",
     "query": "SELECT   (1-(last(\"free\") / last(\"total\")))*100 FROM \"disk\" WHERE (\"device\" = '192.168.1.128:6789,192.168.1.129:6789:/')",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "device",
       "operator": "=",
       "value": "192.168.1.128:6789,192.168.1.129:6789:/"
      }
     ]
    }
   ]
  },
  {
   "title": "Media Pool Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 12 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_device",
     "measurement": "disk",
     "query": "SELECT \"total\" FROM \"disk\" WHERE (\"host\" = 'shockwave' AND \"device\" = '192.168.1.128:6789,192.168.1.129:6789:/')",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "shockwave" },
      {
       "condition": "AND",
       "key": "device",
       "operator": "=",
       "value": "192.168.1.128:6789,192.168.1.129:6789:/"
      }
     ]
    }
   ]
  },
  {
   "title": "Load Avg 1m",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"load1\") FROM \"system\" WHERE \"host\" = 'shockwave' GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "shockwave" }
     ]
    }
   ]
  },
  {
   "title": "Load Avg 5m",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 12 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE \"host\" =~ /^$host$/",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "shockwave" }
     ]
    }
   ]
  },
  {
   "title": "Load Avg 15m",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 12 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"load15\") FROM \"system\" WHERE \"host\" =~ /^$host$/",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "shockwave" }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilzation",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_util",
     "query": "SELECT last(\"pct_pct_system\") + last(\"pct_pct_user\") + last(\"pct_pct_iowait\") + last(\"pct_pct_nice\") + last(\"pct_pct_steal\") as \"utilized\" FROM \"cpu_util\" WHERE (\"host\" = 'shockwave') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct_pct_system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "+" ], "type": "math" }
      ],
      [
       { "params": [ "pct_pct_user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "+" ], "type": "math" }
      ],
      [
       { "params": [ "pct_pct_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "+" ], "type": "math" }
      ],
      [
       { "params": [ "pct_pct_nice" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "+" ], "type": "math" }
      ],
      [
       { "params": [ "pct_pct_steal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "shockwave" }
     ]
    }
   ]
  },
  {
   "title": "Upload",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "format": "KBs",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "txkB_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "shockwave" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "ens6" }
     ]
    }
   ]
  },
  {
   "title": "Cluster Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 14 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ceph",
     "select": [
      [
       { "params": [ "osd_bytes_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Media Pool Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 14 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_device",
     "measurement": "disk",
     "query": "SELECT last(\"total\") - last(\"free\") FROM \"disk\" WHERE (\"host\" = 'shockwave' AND \"device\" = '192.168.1.128:6789,192.168.1.129:6789:/')",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "-" ], "type": "math" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "shockwave" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "192.168.1.127:/" }
     ]
    }
   ]
  },
  {
   "title": "Download",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "format": "KBs",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "rxkB_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "shockwave" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "ens6" }
     ]
    }
   ]
  },
  {
   "title": "Cluster Free",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 16 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ceph",
     "select": [
      [
       { "params": [ "osd_bytes_avail" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Media Pool Free",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 16 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"free\") FROM \"disk\" WHERE (\"host\" = 'shockwave' AND \"device\" = '192.168.1.128:6789,192.168.1.129:6789:/')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "query": "SELECT last(\"load1\") AS \"load1\", last(\"load5\") AS \"load5\", last(\"load15\") AS \"load15\", last(n_cpus) AS \"cpu count\" FROM \"system\" WHERE (\"host\" = 'shockwave') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "load1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "load1" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "shockwave" }
       ]
      }
     ]
    },
    {
     "title": "Network throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "alias": "$tag_device $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "network",
       "query": "SELECT mean(\"rxkB_per_s\") * 8 AS \"in\", mean(\"txkB_per_s\") * 8 AS \"out\" FROM \"network\" WHERE (\"host\" = 'shockwave') AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "rxkB_per_s" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " * 8" ], "type": "math" },
         { "params": [ "in" ], "type": "alias" }
        ],
        [
         { "params": [ "txkB_per_s" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " * 8" ], "type": "math" },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "shockwave" },
        { "condition": "AND", "key": "device", "operator": "=", "value": "ens6" }
       ]
      }
     ]
    },
    {
     "title": "CPU used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu_util",
       "query": "SELECT last(\"pct_pct_steal\") AS \"steal\", last(\"pct_pct_nice\") AS \"nice\", last(\"pct_pct_iowait\") AS \"iowait\", last(\"pct_pct_system\") AS \"system\", last(\"pct_pct_user\") AS \"user\", 100 - last(\"pct_pct_idle\") AS \"total\" FROM \"cpu_util\" WHERE (\"host\" = 'shockwave') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "pct_steal" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "steal" ], "type": "alias" }
        ],
        [
         { "params": [ "pct_nice" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "nice" ], "type": "alias" }
        ],
        [
         { "params": [ "pct_iowait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "iowait" ], "type": "alias" }
        ],
        [
         { "params": [ "system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "system" ], "type": "alias" }
        ],
        [
         { "params": [ "user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "user" ], "type": "alias" }
        ],
        [
         { "params": [ "pct_idle" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "idle" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Per CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_cpu",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT 100 - last(\"usage_idle\") FROM \"cpu\" WHERE (\"host\" = 'shockwave') AND $timeFilter GROUP BY time(5s), \"cpu\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk IO/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "shockwave" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "vda1" }
       ]
      }
     ]
    },
    {
     "title": "Disk throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_name $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT mean(\"rkB_per_s\") AS \"read\", mean(\"wkB_per_s\") AS \"write\" FROM \"disk\" WHERE (\"device\" =~ /^$disk$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($interval), \"device\" fill(null)",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "shockwave" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "vda" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Ceph Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "ceph",
   "collapsed": true,
   "panels": [
    {
     "title": "Ceph Disk Throughput - $ceph",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_name $col",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "diskio",
       "query": "SELECT derivative(last(\"read_bytes\"), 1s) AS \"read\", derivative(last(\"write_bytes\"), 1s) AS \"write\" FROM \"diskio\" WHERE (\"host\" =~ /^$ceph$/ AND \"name\" =~ /^[s|v|m]d([0-9]|[a-z]+)$/) AND $timeFilter GROUP BY \"name\", time($__interval)",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read bytes/sec" ], "type": "alias" }
        ],
        [
         { "params": [ "write_bytes" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write bytes/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^sd[a-z]+$/" }
       ]
      },
      {
       "alias": "$host $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "diskio",
       "query": "SELECT derivative(sum(\"write_bytes\"), 1s) as \"total write\", derivative(sum(\"read_bytes\"), 1s) as \"total read\" FROM \"diskio\" WHERE (\"host\" =~ /^$ceph$/ AND \"name\" =~ /^[s|v|m]d([0-9]|[a-z]+)$/)  AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Ceph OSD IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$ceph$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^[s|d|v][d][a-z|0-9]$/" }
       ]
      },
      {
       "alias": "$tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT derivative(last(\"writes\"), 1s) AS \"write\" FROM \"diskio\" WHERE (\"host\" =~ /^$host$/ AND \"name\" =~ /^[s|d|v][d][a-z|0-9]$/) AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$ceph$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^[s|d|v][d][a-z|0-9]$/" }
       ]
      }
     ]
    },
    {
     "title": "Ceph OSD latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "read_time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "read latency" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$ceph$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^[s|d|v][d][a-z|0-9]$/" }
       ]
      },
      {
       "alias": "$tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "write_time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "write latency" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$ceph$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^[s|d|v][d][a-z|0-9]$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Ceph Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ceph Disk Throughput - $ceph",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_name $col",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "diskio",
       "query": "SELECT derivative(last(\"read_bytes\"), 1s) AS \"read\", derivative(last(\"write_bytes\"), 1s) AS \"write\" FROM \"diskio\" WHERE (\"host\" =~ /^$ceph$/ AND \"name\" =~ /^[s|v|m]d([0-9]|[a-z]+)$/) AND $timeFilter GROUP BY \"name\", time($__interval)",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read bytes/sec" ], "type": "alias" }
        ],
        [
         { "params": [ "write_bytes" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write bytes/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^sd[a-z]+$/" }
       ]
      },
      {
       "alias": "$host $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "diskio",
       "query": "SELECT derivative(sum(\"write_bytes\"), 1s) as \"total write\", derivative(sum(\"read_bytes\"), 1s) as \"total read\" FROM \"diskio\" WHERE (\"host\" =~ /^$ceph$/ AND \"name\" =~ /^[s|v|m]d([0-9]|[a-z]+)$/)  AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Ceph OSD IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$ceph$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^[s|d|v][d][a-z|0-9]$/" }
       ]
      },
      {
       "alias": "$tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT derivative(last(\"writes\"), 1s) AS \"write\" FROM \"diskio\" WHERE (\"host\" =~ /^$host$/ AND \"name\" =~ /^[s|d|v][d][a-z|0-9]$/) AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$ceph$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^[s|d|v][d][a-z|0-9]$/" }
       ]
      }
     ]
    },
    {
     "title": "Ceph OSD latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "read_time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "read latency" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$ceph$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^[s|d|v][d][a-z|0-9]$/" }
       ]
      },
      {
       "alias": "$tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "write_time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "write latency" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$ceph$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^[s|d|v][d][a-z|0-9]$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Ceph Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ceph Disk Throughput - $ceph",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_name $col",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "diskio",
       "query": "SELECT derivative(last(\"read_bytes\"), 1s) AS \"read\", derivative(last(\"write_bytes\"), 1s) AS \"write\" FROM \"diskio\" WHERE (\"host\" =~ /^$ceph$/ AND \"name\" =~ /^[s|v|m]d([0-9]|[a-z]+)$/) AND $timeFilter GROUP BY \"name\", time($__interval)",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read bytes/sec" ], "type": "alias" }
        ],
        [
         { "params": [ "write_bytes" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write bytes/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^sd[a-z]+$/" }
       ]
      },
      {
       "alias": "$host $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "diskio",
       "query": "SELECT derivative(sum(\"write_bytes\"), 1s) as \"total write\", derivative(sum(\"read_bytes\"), 1s) as \"total read\" FROM \"diskio\" WHERE (\"host\" =~ /^$ceph$/ AND \"name\" =~ /^[s|v|m]d([0-9]|[a-z]+)$/)  AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Ceph OSD IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$ceph$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^[s|d|v][d][a-z|0-9]$/" }
       ]
      },
      {
       "alias": "$tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT derivative(last(\"writes\"), 1s) AS \"write\" FROM \"diskio\" WHERE (\"host\" =~ /^$host$/ AND \"name\" =~ /^[s|d|v][d][a-z|0-9]$/) AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$ceph$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^[s|d|v][d][a-z|0-9]$/" }
       ]
      }
     ]
    },
    {
     "title": "Ceph OSD latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "read_time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "read latency" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$ceph$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^[s|d|v][d][a-z|0-9]$/" }
       ]
      },
      {
       "alias": "$tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "write_time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "write latency" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$ceph$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^[s|d|v][d][a-z|0-9]$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}